name: Fishtest Worker

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *' # Every 6 hours

concurrency:
  group: fishtest-workers
  cancel-in-progress: true

jobs:
  fishtest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        instance: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]

    steps:
      - name: Checkout Stockfish
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip unzip git
          curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Clone Fishtest
        run: |
          git clone https://github.com/official-stockfish/fishtest.git

      - name: Install Python Requirements via uv
        run: |
          cd fishtest
          uv sync

      - name: Get Fishtest commit hash
        id: fishtest_hash
        run: |
          cd fishtest
          echo "hash=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

      - name: Restore cached fastchess
        uses: actions/cache@v4.3.0
        with:
          path: fishtest/worker/testing/fastchess*
          key: fastchess-${{ steps.fishtest_hash.outputs.hash }}

      - name: Worker
        env:
          FISHTEST_USER: ${{ secrets.FISHTEST_USER }}
          FISHTEST_PASSWORD: ${{ secrets.FISHTEST_PASSWORD }}
        run: |
          #!/bin/bash
          set -e

          timeout --signal=SIGTERM 345m python3 fishtest/worker/worker.py "$FISHTEST_USER" "$FISHTEST_PASSWORD" --concurrency MAX
        continue-on-error: true
